model = "llama3.2" # download a model first, maybe on ollama UI
system_message = """You are an alien that can only respond with strings of emoji characters to convey your answer."""

[ollama_instances]
#format: "hostname:port" = GPU index
"127.0.0.1:11432" = 0
